### ISSUE TITLE
Intercept Browser Shortcuts

### ISSUE THREAD

**Issue by gregorskii** [UnicornHeartClub/react-keybind#66] opened 2019-02-27 20:35 UTC
This library does not appear to intercept browser keybindings. For instance command+p will be print regardless of what key is setup.

Is this the case? Missing something?

**Comment by Redmega** [comment] 2019-10-16 00:28
Duplicate of https://github.com/UnicornHeartClub/react-keybind/issues/42

**Closed by Redmega** 2019-10-16 00:28 UTC
